import type { RoastPlan } from '@/types/domain';

export const seedRoastPlans: RoastPlan[] = [
  {
    id: 1,
    name: '肯尼亚 柏拉 AA Plus SL28 SL34 水洗',
    beanId: 101,
    beanName: '肯尼亚 柏拉 AA Plus SL28 SL34 水洗',
    roasterModel: 'tank200d',
    batchWeightGrams: 200,
    plannedBatchKg: 0.2,
    targetRoastLevel: '手冲浅烘',
    roastPurpose: '手冲',
    status: 'draft',
    createdAt: '2026-06-26T00:00:00.000Z',
    updatedAt: '2026-06-26T00:00:00.000Z',
    steps: [
      {
        id: 1,
        timeLabel: '0:00',
        eventName: '入豆',
        operation: '入豆',
        drumTemperature: '235°C',
        airTemperature: '210°C',
        firePower: '90%',
        drumSpeed: '45rpm',
      },
      {
        id: 2,
        timeLabel: '1:20~1:30',
        eventName: '回温点',
        operation: '保持',
        drumTemperature: '-',
        airTemperature: '180°C',
        firePower: '90%',
        drumSpeed: '45rpm',
      },
      {
        id: 3,
        timeLabel: '2:00',
        eventName: '前段降火',
        operation: '降火',
        drumTemperature: '-',
        airTemperature: '172°C',
        firePower: '85%',
        drumSpeed: '46rpm',
      },
      {
        id: 4,
        timeLabel: '4:40~5:00',
        eventName: '转黄',
        operation: '降火',
        drumTemperature: '154~158°C（参考）',
        airTemperature: '165°C',
        firePower: '75%',
        drumSpeed: '47rpm',
      },
      {
        id: 5,
        timeLabel: '6:50',
        eventName: '中后段降火',
        operation: '降火',
        drumTemperature: '-',
        airTemperature: '182°C',
        firePower: '65%',
        drumSpeed: '48rpm',
      },
      {
        id: 6,
        timeLabel: '8:50~9:20',
        eventName: '一爆开始',
        operation: '保持',
        drumTemperature: '208±2°C',
        airTemperature: '196°C',
        firePower: '65%',
        drumSpeed: '50rpm',
      },
      {
        id: 7,
        timeLabel: '一爆+20s',
        eventName: '发展阶段',
        operation: '降火',
        drumTemperature: '-',
        airTemperature: '190°C',
        firePower: '55%',
        drumSpeed: '52rpm',
      },
      {
        id: 8,
        timeLabel: '一爆+45s',
        eventName: '发展阶段',
        operation: '降火',
        drumTemperature: '-',
        airTemperature: '188°C',
        firePower: '50%',
        drumSpeed: '52rpm',
      },
    ],
  },
  {
    id: 2,
    name: '埃塞俄比亚 古吉 水洗 浅中烘',
    beanId: 102,
    beanName: '埃塞俄比亚 古吉 水洗',
    roasterModel: '其他',
    batchWeightGrams: 500,
    plannedBatchKg: 0.5,
    targetRoastLevel: '浅中烘',
    roastPurpose: '意式拼配测试',
    status: 'draft',
    createdAt: '2026-06-26T00:00:00.000Z',
    updatedAt: '2026-06-26T00:00:00.000Z',
    steps: [
      {
        id: 1,
        timeLabel: '0:00',
        eventName: '入豆',
        operation: '入豆',
        drumTemperature: '220°C',
        airTemperature: '205°C',
        firePower: '85%',
        drumSpeed: '50rpm',
      },
      {
        id: 2,
        timeLabel: '1:30',
        eventName: '回温点',
        operation: '保持',
        drumTemperature: '-',
        airTemperature: '178°C',
        firePower: '85%',
        drumSpeed: '50rpm',
      },
      {
        id: 3,
        timeLabel: '5:10',
        eventName: '转黄',
        operation: '降火',
        drumTemperature: '155°C',
        airTemperature: '162°C',
        firePower: '70%',
        drumSpeed: '52rpm',
      },
      {
        id: 4,
        timeLabel: '8:40',
        eventName: '一爆开始',
        operation: '保持',
        drumTemperature: '202°C',
        airTemperature: '191°C',
        firePower: '62%',
        drumSpeed: '54rpm',
      },
    ],
  },
];
